# Generated by Django 5.2.7 on 2025-10-08 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pratap Bag Healthcare Clinic', max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('phone_primary', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phone_secondary', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email_primary', models.EmailField(max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for Google Maps', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for Google Maps', max_digits=9, null=True)),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL', null=True)),
                ('monday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=50)),
                ('tuesday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=50)),
                ('wednesday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=50)),
                ('thursday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=50)),
                ('friday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=50)),
                ('saturday_hours', models.CharField(default='9:00 AM - 6:00 PM', max_length=50)),
                ('sunday_hours', models.CharField(default='Closed', max_length=50)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clinic Information',
                'verbose_name_plural': 'Clinic Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Phone number for contact', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.CharField(choices=[('appointment', 'Appointment Inquiry'), ('service', 'Service Information'), ('career', 'Career Inquiry'), ('general', 'General Inquiry'), ('complaint', 'Complaint'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text='Reply from admin', null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
