# Generated by Django 5.2.6 on 2025-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicinfo',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps embed URL', max_length=500, null=True),
        ),
    ]
