# Generated by Django 5.2.6 on 2025-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Catchy title for the blog post', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('youtube_url', models.URLField(help_text='Full YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', max_length=500)),
                ('youtube_video_id', models.CharField(blank=True, help_text='YouTube video ID (automatically extracted from URL)', max_length=20)),
                ('headline', models.CharField(help_text='Brief, engaging headline that summarizes the video content', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the video content and key takeaways')),
                ('key_points', models.TextField(blank=True, help_text='Bullet points of main topics covered (one per line)')),
                ('category', models.CharField(choices=[('physiotherapy', 'Physiotherapy'), ('acupressure', 'Acupressure'), ('massage', 'Massage Therapy'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise & Fitness'), ('wellness', 'General Wellness'), ('alternative_medicine', 'Alternative Medicine'), ('mental_health', 'Mental Health'), ('pain_management', 'Pain Management'), ('rehabilitation', 'Rehabilitation')], default='wellness', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for better search (e.g., back pain, stretching, tips)', max_length=500)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 characters)', max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured to show on homepage')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'), models.Index(fields=['category', 'status'], name='blog_blogpo_categor_a21b24_idx'), models.Index(fields=['is_featured', 'status'], name='blog_blogpo_is_feat_eb28c3_idx')],
            },
        ),
    ]
