# Generated by Django 5.2.6 on 2025-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('payu', 'PayU'), ('paytm', 'Paytm'), ('stripe', 'Stripe')], default='razorpay', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable online payments')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Use test/sandbox mode')),
                ('razorpay_key_id', models.CharField(blank=True, help_text='Razorpay Key ID', max_length=200)),
                ('razorpay_key_secret', models.CharField(blank=True, help_text='Razorpay Key Secret', max_length=200)),
                ('currency', models.CharField(default='INR', help_text='Payment currency code', max_length=3)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum payment amount', max_digits=10)),
                ('convenience_fee_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Convenience fee percentage', max_digits=5)),
                ('convenience_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed convenience fee amount', max_digits=10)),
                ('enable_netbanking', models.BooleanField(default=True)),
                ('enable_cards', models.BooleanField(default=True)),
                ('enable_wallets', models.BooleanField(default=True)),
                ('enable_upi', models.BooleanField(default=True)),
                ('enable_emi', models.BooleanField(default=False)),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for payment updates')),
                ('success_url', models.URLField(blank=True, help_text='Success redirect URL')),
                ('failure_url', models.URLField(blank=True, help_text='Failure redirect URL')),
                ('business_name', models.CharField(default='Pratap Bag Healthcare', help_text='Business name on payment page', max_length=200)),
                ('business_logo', models.ImageField(blank=True, help_text='Logo to show on payment page', null=True, upload_to='payment/')),
                ('terms_url', models.URLField(blank=True, help_text='Terms and conditions URL')),
                ('privacy_url', models.URLField(blank=True, help_text='Privacy policy URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
