# Generated by Django 5.2.6 on 2025-10-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_paymentsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
