# Generated by Django 5.2.6 on 2025-10-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_delete_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='razorpay_webhook_secret',
            field=models.CharField(blank=True, help_text='Razorpay Webhook Secret (for signature verification)', max_length=200),
        ),
    ]
