# Generated by Django 5.2.6 on 2025-10-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_paymentsettings_razorpay_webhook_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='razorpay_webhook_secret',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='practice_start_year',
            field=models.PositiveIntegerField(default=1998, help_text='Year when practice started (used to calculate years of experience)'),
        ),
    ]
