# Generated by Django 5.2.6 on 2025-10-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_remove_paymentsettings_razorpay_webhook_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Page name (will be displayed in footer menu)', max_length=100)),
                ('slug', models.SlugField(help_text='URL slug for the page', max_length=100, unique=True)),
                ('content', models.TextField(help_text='Page content (supports HTML)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('is_active', models.BooleanField(default=True, help_text='Show in footer menu')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in footer menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Page',
                'verbose_name_plural': 'Custom Pages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Bio-Physio Consultant', max_length=200),
        ),
    ]
