# Generated by Django 5.2.6 on 2025-10-15 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_custompage_alter_sitesettings_site_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PractitionerProfile',
        ),
    ]
