# Generated by Django 5.2.6 on 2025-10-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='experience_level',
        ),
    ]
