# Generated by Django 5.2.6 on 2025-10-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_remove_jobopening_experience_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Training Application', 'verbose_name_plural': 'Training Applications'},
        ),
        migrations.AlterModelOptions(
            name='jobopening',
            options={'ordering': ['-created_at'], 'verbose_name': 'New Batch', 'verbose_name_plural': 'New Batches'},
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Exercise Therapy'), ('part_time', 'Magnet Therapy'), ('contract', 'Massage Therapy'), ('internship', 'Physiotherapy'), ('volunteer', 'Acupressure')], default='full_time', max_length=20, verbose_name='Clinical Training'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum tuition fees in INR', max_digits=10, null=True, verbose_name='Tuition Fees (Max)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum tuition fees in INR', max_digits=10, null=True, verbose_name='Tuition Fees (Min)'),
        ),
    ]
