# Generated by Django 5.2.6 on 2025-10-10 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_timeslot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, help_text='When payment was successfully completed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_initiated_at',
            field=models.DateTimeField(blank=True, help_text='When payment was initiated', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (card, upi, netbanking, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay order ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_signature',
            field=models.CharField(blank=True, help_text='Razorpay payment signature for verification', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(help_text='Selected services for this booking', related_name='bookings', to='bookings.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='User who made the booking (required)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total payment amount in INR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='Razorpay payment ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use services field instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_bookings', to='bookings.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('payment_failed', 'Payment Failed')], default='pending', max_length=20),
        ),
    ]
