# Generated by Django 5.2.6 on 2025-10-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_payment_completed_at_and_more'),
    ]

    operations = [
    ]
