# Generated by Django 5.2.6 on 2025-10-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remove_booking_payment_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='requires_prescription',
        ),
    ]
