# Generated by Django 5.2.6 on 2025-10-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_prescriptionupload_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescriptionupload',
            name='patient',
        ),
    ]
